spring.application.name=GhostCoach
jwt.secret=${JWT_KEY}
jwt.expiration=${JWT_EXPIRATION}
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
gemini.api.key=${GEMINI_API_KEY}
gemini.api.endpoint=${GEMINI_API_ENDPOINT}
